# Generated by Django 4.2.2 on 2023-06-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_barcode_id', models.CharField(max_length=50, unique=True)),
                ('membership_length', models.IntegerField(default=0)),
            ],
        ),
    ]
